#travis ci config script


language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -q

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo apt-get install -qq python3 libglew-dev libftgl-dev libfreetype6-dev libfontconfig1-dev libsdl2-dev libsdl2-image-dev

before_script:
  - echo starting test build nao

script:
  - ./configure && make

after_script:
  - echo test build exited

notifications:
#  recipients:
#    - lol@mail.ie
#    - rofl@liam.ei
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#sfttech"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
#env:
#  - BUILDMODE=debug
#  - BUILDMODE=release
