name: MacOSX-CI
on: [push, pull_request]

jobs:
  macosx-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Brew update-reset
        run: brew update-reset
      - name: Brew update
        run: brew update
      - name: Brew install DeJaVu fonts
        run: brew tap homebrew/cask-fonts && brew cask install font-dejavu
      - name: Upgrade cmake
        run: brew upgrade cmake
      - name: Install dependencies with homebrew
        run: brew install freetype cmake python3 qt5 flex make libepoxy fontconfig harfbuzz sdl2 sdl2_image opus libogg opusfile libpng eigen
      - name: Install LLVM
        run: brew install -cc=clang llvm@8
      - name: Setting environment variables
        run: export PATH="/usr/local/opt/llvm@8/bin:$PATH:/usr/local/lib:/usr/local/opt/llvm/bin" && export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/local/lib"
      - name: Install python3 dependencies
        run: pip3 install pygments cython numpy pillow pyreadline jinja2
      - name: Configure 
        run: ./configure --compiler=clang++ --mode=debug --download-nyan 
      - name: Build
        run: make
      - name: Test
        run: make test
